### ISSUE TITLE
Doesn´t work

### ISSUE THREAD

**Issue by gate0keeper** [Blacksmoke16/buyBack#1]
Hi,

can´t get it to work. It does not gets prices from stuff I pasted into box and also did not even react on submit try´s. Database is created, everything like description. Please could you go over and look if you find an error?

Thanks, Sylvi

**Comment by Blacksmoke16** [comment]
A few things to confirm:
1.  Did you load invTypes table?
2.  Does the item name and quantity show up in the box?
3.  Can you successfully submit to the buyback table?
4.  Is the item groupID in the list of valid groupIDs?

**Comment by gate0keeper** [comment]
Hi Blacksmoke16,


thanks for the fast reply :)
Well, lets answer your questions:

1. Nope, it stays under requirements, but I don´t know what to do there
2. Nope, when copying to the input field I see some reactions from the website, it changes state to unsecure in top of browser, thats all. The Table below stays clear, no value is added above the input field
3. Nope, there is no way to submit the form
4. Yes and no, I tried both, also like your screenshot shows it. 

Thanks for your time :)

**Comment by Blacksmoke16** [comment]
Part of your issue is you do not have the invTypes table loaded into your DB.  

You can get a copy of that from there:  https://www.fuzzwork.co.uk/dump/latest/invTypes.sql.bz2

Get that table loaded in and see if that helps.

**Comment by gate0keeper** [comment]
Ok, so I have loaded it inside, my db structure looks like that:

buyback_history
invTypes

Behavior stays the same...

**Comment by Blacksmoke16** [comment]
Convo me in game and we'll see if we can get it figured out.  It's been a while since i used this.

**Comment by gate0keeper** [comment]
Kind of strange for me, as I haven´t seen before is the following:

1. In config.php: $schema = 'SCHEMA'; (Tried to input the the DB name, as I have read it would be so)
2. In submit php: $con = mysqli_connect($hostName, $userName, $password, 'buyback'); (The last point buyback,if the table is meant, it would be buyback_history)
3. Finally in config.js:

        // Path to itemData PHP script
        $rootScope.ITEM_DATA_URL = '/buyBack/PHP/itemData.php';

        // Path to submit PHP script
        $rootScope.SUBMIT_URL = '/buyBack/PHP/submit.php';

From index I have no /buyback/ before, I also tried to remove it, but it does not work too.
Well, I will hit you ingame, perhaps you can help me further with some corp/web stuff :)
